batchsize: 4
batchsize_test: 10
iteration: 200000
iteration_decay_start: 150000
seed: 0
display_interval: 100
progressbar_interval: 100
snapshot_interval: 20000
evaluation_interval: 2000

models:
  generator:
    fn: gen_models/resunet.py
    name: ResUNetGenerator
    args:
      ch: 64
      normalization: groupnorm
      learnable_skip: True
      downsample: False

  discriminator:
      fn: dis_models/resnet.py
      name: ConcatResNetDiscriminator
      args:
        x_channels: 1
        y_channels: 3

dataset:
  fn: datasets/rgnirsar.py
  name: paired_sar_rgnir
  args:
    dir_paired_sar: /projects/g-nedo-geospatial/work/enomoto/data_CloudRemoval/image_data/RGNIRSAR/TRAIN/paired_sar_256
    dir_paired_rgnir: /projects/g-nedo-geospatial/work/enomoto/data_CloudRemoval/image_data/RGNIRSAR/TRAIN/paired_rgnir_256
    imlist_paired_sar: supp_info/paired_sar_256.txt
    imlist_paired_rgnir: supp_info/paired_rgnir_256.txt
    size: 128
    augmentation: True
    rate_train: 0.95

adam:
  alpha: 0.0002
  beta1: 0.5
  beta2: 0.999

updater:
  fn: updaters/updater_pix2pix.py
  name: Updater
  args:
    n_dis: 1
    loss_type: dcgan
    weight_l1: 100

evaluation:
  fn: evaluations/evaluation.py
  name: out_image
